---
- hosts: declan-desktop
  roles: 
    - home_install
    - common_applications
    - intensive_applications
    - ansible
    - latex
    - discord
    - spotify
    - minecraft_server
    - minecraft_client
    - steam
    - {role: i3, monitors: 2}
