---
- set_fact:
    outer_loop: "{{ item }}"
 
- name: "Check if {{ outer_loop.application }} is the default {{ outer_loop.mime }} viewer"
  command: "xdg-mime query default {{ outer_loop.mime }}"
  register: default_application
  changed_when: False

- name: "Set {{ outer_loop.application }} to the default {{ outer_loop.mime }} viewer"
  command: "xdg-mime default {{ outer_loop.application }} {{ outer_loop.mime }}"
  when: outer_loop.application is not match(default_application.stdout)
