---
- name: Set vim as Visual
  become: yes
  lineinfile:
    path: "/home/{{ user }}/.profile"
    regexp: '^VISUAL='
    line: 'VISUAL=vim'

- name: Set Vim as default editor
  become: yes
  lineinfile:
    path: "/home/{{ user }}/.profile"
    regexp: '^EDITOR='
    line: 'EDITOR=$VISUAL'

- name: Create git config
  template:
    src: gitconfig
    dest: "/home/{{ user }}/.gitconfig"
    mode: 0664
    owner: "{{ user }}"
    group: "{{ user }}"
