---
- include: install.yml
- include: git_configs.yml
- include: vim_configs.yml
- include: tmux_configs.yml
- include_vars: ventoy.yml
- include: ventoy.yml
- include: default_application.yml
  with_items:
    - {application: "org.pwmt.zathura-pdf-poppler.desktop", mime: "application/pdf"}
