---
#- name: Check if hotkey is taken
#  lineinfile:
#    path: "~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml" 
#    regexp: "{{ shortcut }}"
#  check_mode: yes
#  register: conf
#  failed_when: never

#- name: Delete hotkey
#  command: 
- set_fact:
   outer_loop: "{{ item }}"

# xfconf-query --channel xfce4-keyboard-shortcuts -lv lists all keyboard shortcuts
# You can run this command to see the name of the action you want to set.
- name: "Check if hotkey exists for {{ outer_loop.command }}"
  shell: 'xfconf-query --channel xfce4-keyboard-shortcuts -lv | egrep "{{ outer_loop.shortcut }}.*{{ outer_loop.command }}"'
  register: hotkey_does_not_exist
  #failed_when: hotkey_does_not_exist.rc|int == 0 or hotkey_does_not_exist.rc|int == 1
  failed_when: hotkey_does_not_exist.rc != 0 and hotkey_does_not_exist.rc != 1
  changed_when: false
  
- name: "Add hotkey for {{ outer_loop.command }}"
  command: 'xfconf-query --create --channel xfce4-keyboard-shortcuts --property "/{{ outer_loop.manager }}/custom/{{ outer_loop.shortcut }}" --type string --set "{{ outer_loop.command }}"'
  when: hotkey_does_not_exist.rc

# To add
# Tile Left - super + left arrow
# Tile right - super + right arrow
# maximise - super + up arrow
# minimise - super + down arrow
# xfce4-terminal - super + enter
