# Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
# Will include all hosts the playbook is run on.
# Taken from, with updates https://gist.github.com/rothgar/8793800

- debug:
    var: groups['all']

- debug:
    var: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['all'] }}"

- name: "Build hosts file based on ansible inventory"
  become: yes
  lineinfile:
    dest: /etc/hosts 
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
    state: present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['all'] }}"
