---
- set_fact:
    outer_loop: "{{ item }}"

- name: "Check gsetting {{ outer_loop.setting }} {{ outer_loop.field }}"
  shell: "gsettings get {{ outer_loop.setting }} {{ outer_loop.field }}"
  register: output
  changed_when: false

- name: "Set gsetting {{ outer_loop.setting }} {{ outer_loop.field }} to {{ outer_loop.state }}"
  shell: "gsettings set {{ outer_loop.setting }} {{ outer_loop.field }} {{ outer_loop.state }}"
  when: output.stdout != outer_loop.state
