---
- set_fact:
    outer_loop: "{{ item }}"

- name: Check gsetting is not yet set
  shell: "gsettings get {{ outer_loop.setting }} {{ outer_loop.field }}"
  register: output
  changed_when: false

- name: Set gsetting to desired state
  shell: "gsettings set {{ outer_loop.setting }} {{ outer_loop.field }} {{ outer_loop.state }}"
  when: output.stdout != outer_loop.state
