---
- set_fact:
   outer_loop: "{{ item }}"

- name: "Check setting for {{ outer_loop.setting }} {{ outer_loop.command }}"
  shell: 'gsettings get {{ outer_loop.setting }} {{ outer_loop.command }}'
  register: gsetting
  changed_when: false
  
- name: "Set setting for {{ outer_loop.setting }} {{ outer_loop.command }} to {{ outer_loop.state }}"
  shell: 'gsettings set {{ outer_loop.setting }} {{ outer_loop.command }} {{ outer_loop.state }}'
  when: gsetting.changed
