---
- include: ansible_ppa.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- include: install.yml

  #- include: clone_repo.yml
  #  with_items:
  #    - {directory: "ansible", repo_url: "https://github.com/decyne/ansible-home"}

- include: module_folder.yml
- include: clone_repo.yml
  with_items:
    - {directory: "ansible_modules/ansible-yay", repo_url: "https://github.com/mnussbaum/ansible-yay"}
    - {directory: "ansible_modules/rclone-hosts", repo_url: "https://github.com/stefangweichinger/ansible-rclone.git"}
#- include: install_module.yml
#  with_items:
#    - {location: "ansible-yay", name: "yay"}
- include: link_role.yml
  with_items:
    - {role: "rclone-hosts" }
