---
- name: Install discord
  become: yes
  snap:
    name: discord
    state: present
  register: discord_install

- name: Allow discord to observe unconfined
  become: yes
  command: snap connect discord:system-observe
  when: discord_install.changed
