" Install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Specify a directory for plugins
" Run :PlugInstall in in Vim to install
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes
Plug 'lervag/vimtex'
Plug 'vimwiki/vimwiki'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }

" Initialize plugin system
call plug#end()

set ai et ts=2 sw=2
autocmd FileType yaml setlocal sts=2 nu rnu cuc

set nocompatible
filetype plugin on
syntax on

" vimwiki
let SandV = {}
let SandV.path = '~/Tresors/RPGs/RPGs/Scum and Villainy/Campaign/wiki'
let SandV.path_html = '~/Tresors/RPGs/RPGs/Scum and Villainy/Campaign/wiki_html'

let Stonetop = {}
let Stonetop.path = '~/RPG_Repos/stonetop/wiki'
let Stonetop.path_html = '~/RPG_Repos/stonetop/wiki_html'
let Stonetop.syntax = 'markdown'
let Stonetop.ext = '.md'

let Illmire = {}
let Illmire.path = '~/Tresors/RPGs/RPGs/Illmire/Campaign/wiki'
let Illmire.path_html = '~/Tresors/RPGs/RPGs/Illmire/Campaign/wiki_html'
let Illmire.syntax = 'markdown'
let Illmire.ext = '.md'

let Painting = {}
let Painting.path = '~/RPG_Repos/Miniatures/Painting/wiki'
let Painting.path_html = '~/RPG_Repos/Miniatures/Painting/wiki_html'
let Painting.syntax = 'markdown'
let Painting.ext = '.md'

let g:vimwiki_list = [SandV,Stonetop,Illmire,Painting]
